version: '3'
services:
    mongodb:
      image: mongo
      ports: 
       - 27017:27017
      environment:
       - MONGO_INITDB_ROOT_USERNAME=admin
       - MONGO_INITDB_ROOT_PASSWORD=pass

    mongo-express:
      image: mongo-express
      ports: 
       - 8081:8081
      environment:
       - ME_CONFIG_MONGODB_ENABLE_ADMIN='true'
       - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
       - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
       - ME_CONFIG_MONGODB_SERVER=mongoDB

